# Use OpenJDK as the base image for a Java runtime environment
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Gradle into the container
# The JAR file should be inside the build/libs folder after a successful Gradle build
COPY build/libs/Login_Findr-0.0.1-SNAPSHOT.jar app.jar

# Expose the port that your app will run on (default is 8080)
EXPOSE 8080

# Command to run the JAR file when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
