services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-rapid-dew-a4323185-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_e8nkLGpAtcB6
    volumes:
      - /dev/shm:/dev/shm  # Required for Chrome/Selenium