spring:
  datasource:
    # H2 CONFIG (disabled)
    # url: jdbc:h2:mem:login-db
    # driver-class-name: org.h2.Driver
    # username: sa
    # password:

    # POSTGRES CONFIG (disabled)
    # url: jdbc:postgresql://localhost:5432/peoplehub
    # driver-class-name: org.postgresql.Driver
    # username: postgres
    # password: 1234

    #For NEON DB SetUp
    url: jdbc:postgresql://ep-rapid-dew-a4323185-pooler.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_e8nkLGpAtcB6
    hikari:
      data-source-properties:
        sslmode: require

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# H2 console (disabled)
# spring:
#   h2:
#     console:
#       enabled: true

# Optional custom port
# server:
#   port: 8080
